//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgEmployee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Enrollments = new HashSet<Enrollment>();
        }
    
        [DisplayName("Employee ID")]
        public int EmployeeID { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [DisplayName("First Name")]
        public string FirstName { get; set; }

        [DisplayName("Joining Date")]
        public Nullable<System.DateTime> JoiningDate { get; set; }
    
        public virtual ICollection<Enrollment> Enrollments { get; set; }
    }
}
