//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrgEmployee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Enrollment
    {
        [DisplayName("Enrollment ID")]
        public int EnrollmentID { get; set; }

        [DisplayName("Band")]
        public Nullable<decimal> Band { get; set; }

        public int DepartmentID { get; set; }

        public int EmployeeID { get; set; }

        [DisplayName("Department")]
        public virtual Department Department { get; set; }

        [DisplayName("Employee")]
        public virtual Employee Employee { get; set; }
    }
}
